export * from './blog.api';
export * from './comapny.api';
export * from './course.api';
export * from './evaluation.api';
export * from './event.api';
export * from './home.api';
export * from './product.api';
export * from './service.api';
export * from './page.api';
